### ISSUE TITLE
Looks like i have a corrupted tree

### ISSUE THREAD

**Issue by kmligue** [gazsp/baum#13] opened 2016-02-25 13:45 UTC
I'm using the old library. I'm thinking it would be better to post my issue here since this repo is being maintained. There is a problem on the parent node because lft column is bigger than rgt column

![ss2](https://cloud.githubusercontent.com/assets/6349162/13321165/57f5143c-dc08-11e5-9f69-32757ea73b24.png)

Also this one. The parent_id is 215 but lft and rgt is not within the parent's lft and rgt

![ss3](https://cloud.githubusercontent.com/assets/6349162/13321233/c0f5e75e-dc08-11e5-9f22-4264b3b836db.png)

I hope someone could help me how to fix this. Also this parent node(215) is the last node in the tree. There are no problems in other nodes. Only this one which is the last one.

**Comment by jonaholsson** [comment] 2016-02-29 13:48
If I understood your questions correct, you could generate a new parent_id column from the existing left and right values. Then use the new parent_id values to regenerate left and right values.

**Comment by gazsp** [comment] 2016-03-27 15:10
@kmligue Do you have any idea how the tree got corrupted? I.e. do you have any steps we can use to reproduce the problem? I've seen this issue before in other MPTT libraries, and it's always difficult to track down what the problem is.

**Comment by poing** [comment] 2020-12-16 23:58
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transfered to a consolidated issue.

**Closed by poing** 2020-12-16 23:58 UTC
